### ISSUE TITLE
Bug: 使用 I'm Feeling Lucky 功能时,会额外打开一个空白标签页

### ISSUE THREAD

**Issue by sabertazimi** [coyove/awesome-v2ex#3]
### 环境
-   System: Linux 4.4.0-28-generic #47-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 16.04 LTS)
-   Mozilla Firefox 47.0
### 描述

每当在 http://v2ex.chann.org/ 点击一次 "I'm feeling lucky"时, 除去打开新的博客页面,还会自动打开一个新的空白标签页.

**Comment by coyove** [comment]
使用了saucelab提供的FF 47在OS X El Capitan、Mavericks和Windows 10、8、7上测试都没有发现这种情况。Ubuntu没有条件测试。

个人猜测是target=_blank这个属性的问题，现在姑且先把这个删去

**Comment by sabertazimi** [comment]
现在OK了,不会再额外弹出空白页了
